name: Deploy to Google Cloud

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup jq
      run: sudo apt update && sudo apt install jq -y

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@master
      with:
        project_id: ${{ secrets.GCE_PROJECT }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Configure gcloud account
      run: |-
        gcloud info
        gcloud config set compute/zone asia-south1-a
        gcloud config set compute/region asia-south1

    - name: Test commands
      run: |
        gcloud compute instances list
